/**
 * CurrentAffairsRuntimeContract — 统一时政运行时契约。
 *
 * 单一 versioned contract 覆盖 research/approve/export/cancel/recover 全生命周期。
 * 替代分散的 currentAffairs:* 与 ca:* 重复语义，所有 IPC 边界必须通过 strict decode。
 */
import { z } from 'zod';
import { createHmac, randomBytes } from 'node:crypto';

export const CA_RUNTIME_CONTRACT_VERSION = 1 as const;

// ── Primitives ─────────────────────────────────────────────────

/** Safe ID: no C0/C1 control chars, no path separators, no whitespace, 1–256 chars. */
// eslint-disable-next-line no-control-regex
const SAFE_ID_CONTROLS = /[\x00-\x1F\x7F-\x9F]/u;
const SAFE_ID_PATH = /[\\/]/u;
const SAFE_ID_WHITESPACE = /\s/u;

const SafeIdSchema = z.string()
  .min(1)
  .max(256)
  .refine((v) => !SAFE_ID_CONTROLS.test(v), { message: 'ID contains control characters' })
  .refine((v) => !SAFE_ID_PATH.test(v), { message: 'ID contains path separators' })
  .refine((v) => !SAFE_ID_WHITESPACE.test(v), { message: 'ID contains whitespace' });

const SafeDigestSchema = z.string().regex(/^[a-f0-9]{64}$/u);

// ── Research ───────────────────────────────────────────────────

export const CurrentAffairsResearchRequestSchema = z.strictObject({
  version: z.literal(CA_RUNTIME_CONTRACT_VERSION),
  operationId: SafeIdSchema,
  projectId: SafeIdSchema,
  workflowId: SafeIdSchema,
  profileId: SafeIdSchema,
  manifestVersion: z.number().int().positive(),
  title: z.string().min(1).max(1000),
  selectedSourceIds: z.array(SafeIdSchema).min(1).max(500),
  facts: z.array(z.strictObject({
    claimId: SafeIdSchema, statement: z.string().min(1).max(8000),
    evidenceSourceIds: z.array(SafeIdSchema).min(1).max(20),
  })).optional(),
  stances: z.array(z.strictObject({
    claimId: SafeIdSchema,
    stance: z.enum(['supports','contradicts','neutral','mixed']),
    rationale: z.string().min(1).max(4000),
    sourceId: SafeIdSchema,
  })).optional(),
  interpretations: z.array(z.strictObject({
    claimId: SafeIdSchema,
    interpretation: z.string().min(1).max(8000),
    synthesizesClaimIds: z.array(SafeIdSchema).min(1).max(20),
  })).optional(),
});
export type CurrentAffairsResearchRequest = z.infer<typeof CurrentAffairsResearchRequestSchema>;

/** Public receipt — no HMAC signature, no owner. Safe for renderer. */
export const PublicApprovalReceiptSchema = z.strictObject({
  receiptId: SafeIdSchema,
  nonce: SafeIdSchema,
  expiresAt: z.number().int().min(0),
  projectId: SafeIdSchema,
  workflowId: SafeIdSchema,
  profileId: SafeIdSchema,
  manifestVersion: z.number().int().positive(),
  contentDigest: SafeDigestSchema,
  sourceSnapshotDigest: SafeDigestSchema,
});
export type PublicApprovalReceipt = z.infer<typeof PublicApprovalReceiptSchema>;

/** Renderer-safe preview section — generated by main, consumed by Panel. */
const PreviewSectionSchema = z.strictObject({
  heading: z.string().min(1).max(256),
  content: z.string().max(50_000),
});

export const CurrentAffairsResearchResponseSchema = z.discriminatedUnion('ok', [
  z.strictObject({
    ok: z.literal(true),
    version: z.literal(CA_RUNTIME_CONTRACT_VERSION),
    operationId: SafeIdSchema,
    draft: z.literal(true),
    readyForApproval: z.literal(true),
    phase: z.literal('approval'),
    approved: z.literal(false), // approval requires receipt — never self-approved
    exportReady: z.literal(false), // only true after approve+markApproved
    temporalCheckPassed: z.boolean(),
    correctionReviewComplete: z.boolean(),
    verifiedSourceCount: z.number().int().min(0),
    rejectedSourceCount: z.number().int().min(0),
    sourceCount: z.number().int().min(0),
    factCount: z.number().int().min(0),
    contentDigest: SafeDigestSchema,
    sourceSnapshotDigest: SafeDigestSchema,
    /** Renderer-safe preview generated by main from canonical manifest + workflow state. */
    preview: z.strictObject({
      title: z.string().min(1).max(1000),
      summary: z.string().max(2000),
      sections: z.array(PreviewSectionSchema).max(20),
      sourceCount: z.number().int().min(0),
      factCount: z.number().int().min(0),
    }),
    errors: z.array(z.string()),
  }),
  z.strictObject({
    ok: z.literal(false),
    version: z.literal(CA_RUNTIME_CONTRACT_VERSION),
    operationId: SafeIdSchema,
    code: z.enum(['manifest_invalid','repository_unavailable','source_load_failed','no_valid_sources','workflow_validation_failed','context_save_failed']),
    errors: z.array(z.string()),
  }),
]);
export type CurrentAffairsResearchResponse = z.infer<typeof CurrentAffairsResearchResponseSchema>;

// ── Approval Receipt ───────────────────────────────────────────

export const ApprovalReceiptSchema = z.strictObject({
  receiptId: SafeIdSchema,
  requestId: SafeIdSchema,
  projectId: SafeIdSchema,
  workflowId: SafeIdSchema,
  profileId: SafeIdSchema,
  manifestVersion: z.number().int().positive(),
  ownerSessionId: SafeIdSchema,
  contentDigest: SafeDigestSchema,
  sourceSnapshotDigest: SafeDigestSchema,
  nonce: SafeIdSchema,
  issuedAt: z.number().int().min(0),
  expiresAt: z.number().int().min(0),
  approved: z.boolean(),
  /** HMAC-SHA256 signature over ALL receipt fields (including projectId/workflowId/manifestVersion). */
  signature: SafeDigestSchema.optional(),
});
export type ApprovalReceipt = z.infer<typeof ApprovalReceiptSchema>;

export function isReceiptExpired(receipt: ApprovalReceipt, now: number): boolean {
  return now > receipt.expiresAt;
}

export function isReceiptValid(receipt: ApprovalReceipt, contentDigest: string, now: number): boolean {
  if (!receipt.approved) return false;
  if (isReceiptExpired(receipt, now)) return false;
  if (receipt.contentDigest !== contentDigest) return false;
  return true;
}

export function createReceiptFingerprint(receipt: ApprovalReceipt): string {
  return [
    receipt.receiptId, receipt.projectId, receipt.workflowId,
    receipt.profileId, String(receipt.manifestVersion),
    receipt.ownerSessionId, receipt.contentDigest,
    receipt.sourceSnapshotDigest, receipt.nonce,
  ].join(':');
}

/** Canonical payload for HMAC signing — ALL fields must be covered. */
function receiptSigningPayload(receipt: Omit<ApprovalReceipt, 'signature'>): string {
  return [
    receipt.receiptId,
    receipt.requestId,
    receipt.projectId,
    receipt.workflowId,
    receipt.profileId,
    String(receipt.manifestVersion),
    receipt.ownerSessionId,
    receipt.contentDigest,
    receipt.sourceSnapshotDigest,
    receipt.nonce,
    String(receipt.issuedAt),
    String(receipt.expiresAt),
    String(receipt.approved),
  ].join(':');
}

/** Minimum secret length for HMAC-SHA256 signing security. */
export const RECEIPT_MIN_SECRET_BYTES = 32;

/** Sign a receipt with HMAC-SHA256 using the provided secret.
 *  Throws if secret is shorter than RECEIPT_MIN_SECRET_BYTES. */
export function signReceipt(
  receipt: Omit<ApprovalReceipt, 'signature'>,
  secret: Buffer,
): ApprovalReceipt {
  if (secret.length < RECEIPT_MIN_SECRET_BYTES) {
    throw new Error(`Receipt signing secret must be at least ${RECEIPT_MIN_SECRET_BYTES} bytes (got ${secret.length})`);
  }
  const payload = receiptSigningPayload(receipt);
  const signature = createHmac('sha256', secret).update(payload).digest('hex');
  return { ...receipt, signature };
}

/** Verify a receipt's HMAC signature. Returns false if signature missing or invalid. */
export function verifyReceiptSignature(receipt: ApprovalReceipt, secret: Buffer): boolean {
  if (!receipt.signature) return false;
  const { signature, ...unsigned } = receipt;
  const payload = receiptSigningPayload(unsigned);
  const expected = createHmac('sha256', secret).update(payload).digest('hex');
  return cryptoTimingSafeEqual(Buffer.from(signature), Buffer.from(expected));
}

/** Generate a new receipt-signing secret (survives restarts via caller persistence). */
export function generateReceiptSecret(): Buffer {
  return randomBytes(32);
}

/** Constant-time comparison to prevent timing attacks on HMAC verification. */
function cryptoTimingSafeEqual(a: Buffer, b: Buffer): boolean {
  if (a.length !== b.length) return false;
  let result = 0;
  for (let i = 0; i < a.length; i++) {
    result |= a[i]! ^ b[i]!;
  }
  return result === 0;
}

// ── Approval Request ───────────────────────────────────────────

export const CurrentAffairsApproveRequestSchema = z.strictObject({
  version: z.literal(CA_RUNTIME_CONTRACT_VERSION),
  operationId: SafeIdSchema,
  projectId: SafeIdSchema,
  workflowId: SafeIdSchema,
  profileId: SafeIdSchema,
  manifestVersion: z.number().int().positive(),
  contentDigest: SafeDigestSchema,
  sourceSnapshotDigest: SafeDigestSchema,
  // No ownerSessionId — main derives from IPC event
});
export type CurrentAffairsApproveRequest = z.infer<typeof CurrentAffairsApproveRequestSchema>;

export const CurrentAffairsApproveResponseSchema = z.discriminatedUnion('ok', [
  z.strictObject({
    ok: z.literal(true),
    version: z.literal(CA_RUNTIME_CONTRACT_VERSION),
    operationId: SafeIdSchema,
    receipt: PublicApprovalReceiptSchema
  }),
  z.strictObject({
    ok: z.literal(false),
    version: z.literal(CA_RUNTIME_CONTRACT_VERSION),
    operationId: SafeIdSchema,
    code: z.enum(['approval_unavailable','receipt_forged','digest_mismatch','already_approved','source_stale','signing_key_unavailable','no_pending_research','approve_mark_failed','approval_denied','cross_owner','content_changed','snapshot_changed','version_mismatch','profile_mismatch']),
  }),
]);
export type CurrentAffairsApproveResponse = z.infer<typeof CurrentAffairsApproveResponseSchema>;

// ── Export Request (receipt-gated) ─────────────────────────────

export const CurrentAffairsExportRequestSchema = z.strictObject({
  version: z.literal(CA_RUNTIME_CONTRACT_VERSION),
  operationId: SafeIdSchema,
  projectId: SafeIdSchema,
  workflowId: SafeIdSchema,
  profileId: SafeIdSchema,
  manifestVersion: z.number().int().positive(),
  contentDigest: SafeDigestSchema,
  receiptId: SafeIdSchema,
  receiptNonce: SafeIdSchema,
  sourceSnapshotDigest: SafeDigestSchema,
  // No ownerSessionId — main derives from IPC event
});
export type CurrentAffairsExportRequest = z.infer<typeof CurrentAffairsExportRequestSchema>;

export const CurrentAffairsExportResponseSchema = z.discriminatedUnion('ok', [
  z.strictObject({
    ok: z.literal(true),
    version: z.literal(CA_RUNTIME_CONTRACT_VERSION),
    operationId: SafeIdSchema,
    artifactId: SafeIdSchema,
    artifactVersion: z.number().int().positive(),
    contentDigest: SafeDigestSchema,
    gatePassed: z.boolean(),
    gateIssues: z.array(z.strictObject({
      gate: z.string(),
      severity: z.enum(['warning','error']),
      message: z.string(),
    })),
    recordCount: z.number().int().min(0),
    provenance: z.strictObject({
      exportedAt: z.number().int().min(0),
      exportedBy: SafeIdSchema,
      receiptId: SafeIdSchema,
      sourceCount: z.number().int().min(0),
    }),
  }),
  z.strictObject({
    ok: z.literal(false),
    version: z.literal(CA_RUNTIME_CONTRACT_VERSION),
    operationId: SafeIdSchema,
    code: z.enum([
      'export_unavailable','receipt_missing','receipt_expired','receipt_forged',
      'content_changed','approval_required','gate_blocked','artifact_create_failed',
      'source_stale','source_retracted','source_not_found',
      'not_approved','no_pending_research','snapshot_changed',
      'build_failed','write_failed','readback_failed','readback_digest_mismatch',
      'readback_file_count_mismatch','readback_file_mismatch','commit_failed',
      'visibility_uncertain','receipt_replayed','receipt_already_reserved',
      'project_mismatch','workflow_mismatch','profile_mismatch',
      'version_mismatch','owner_mismatch','snapshot_mismatch',
      'receipt_not_approved','cross_owner',
    ]),
    artifactId: SafeIdSchema.optional(),
    artifactVersion: z.number().int().positive().optional(),
  }),
]);
export type CurrentAffairsExportResponse = z.infer<typeof CurrentAffairsExportResponseSchema>;

// ── Cancel / Recover ───────────────────────────────────────────

export const CurrentAffairsCancelRequestSchema = z.discriminatedUnion('action', [
  z.strictObject({
    action: z.literal('discard_draft'),
    version: z.literal(CA_RUNTIME_CONTRACT_VERSION),
    operationId: SafeIdSchema,
    projectId: SafeIdSchema,
    workflowId: SafeIdSchema,
  }),
  z.strictObject({
    action: z.literal('revoke_approval'),
    version: z.literal(CA_RUNTIME_CONTRACT_VERSION),
    operationId: SafeIdSchema,
    projectId: SafeIdSchema,
    workflowId: SafeIdSchema,
    profileId: SafeIdSchema,
    manifestVersion: z.number().int().positive(),
    contentDigest: SafeDigestSchema,
    sourceSnapshotDigest: SafeDigestSchema,
    receiptId: SafeIdSchema,
    receiptNonce: SafeIdSchema,
  }),
]);
export type CurrentAffairsCancelRequest = z.infer<typeof CurrentAffairsCancelRequestSchema>;

export const CurrentAffairsCancelResponseSchema = z.discriminatedUnion('ok', [
  z.strictObject({ ok: z.literal(true), version: z.literal(CA_RUNTIME_CONTRACT_VERSION), operationId: SafeIdSchema, action: z.enum(['discard_draft','revoke_approval']) }),
  z.strictObject({ ok: z.literal(false), version: z.literal(CA_RUNTIME_CONTRACT_VERSION), operationId: SafeIdSchema, code: z.enum(['cancel_unavailable','no_pending_context','receipt_not_found','already_exported','not_approved','cross_owner','already_approved_use_revoke','receipt_validation_failed','revoke_failed']) }),
]);
export type CurrentAffairsCancelResponse = z.infer<typeof CurrentAffairsCancelResponseSchema>;

// ── Decoders ───────────────────────────────────────────────────

export function decodeCurrentAffairsResearchResponse(input: unknown): CurrentAffairsResearchResponse {
  const parsed = CurrentAffairsResearchResponseSchema.safeParse(input);
  return parsed.success ? parsed.data : {
    ok: false, version: CA_RUNTIME_CONTRACT_VERSION, operationId: 'decode-recovery',
    code: 'repository_unavailable', errors: ['Failed to decode research response'],
  };
}

export function decodeCurrentAffairsApproveResponse(input: unknown): CurrentAffairsApproveResponse {
  const parsed = CurrentAffairsApproveResponseSchema.safeParse(input);
  return parsed.success ? parsed.data : { ok: false as const, version: CA_RUNTIME_CONTRACT_VERSION, operationId: 'decode-recovery', code: 'approval_unavailable' as const };
}

export function decodeCurrentAffairsCancelResponse(input: unknown): CurrentAffairsCancelResponse {
  const parsed = CurrentAffairsCancelResponseSchema.safeParse(input);
  return parsed.success ? parsed.data : { ok: false as const, version: CA_RUNTIME_CONTRACT_VERSION, operationId: 'decode-recovery', code: 'cancel_unavailable' as const };
}

export function decodeCurrentAffairsExportResponse(input: unknown): CurrentAffairsExportResponse {
  const parsed = CurrentAffairsExportResponseSchema.safeParse(input);
  return parsed.success ? parsed.data : { ok: false as const, version: CA_RUNTIME_CONTRACT_VERSION, operationId: 'decode-recovery', code: 'export_unavailable' as const };
}

// ── List Sources (main-derived safe DTO) ─────────────────────────

const LISTABLE_CA_KINDS = ['policy_document','official_statistics','authoritative_news','legislative_record','regulatory_filing','expert_testimony','institutional_report'] as const;

export const CASourceEntrySchema = z.strictObject({
  sourceId: SafeIdSchema,
  projectId: SafeIdSchema,
  title: z.string().min(1).max(1000),
  kind: z.enum(LISTABLE_CA_KINDS).nullable(),
  authors: z.array(z.string().max(256)).max(50),
  url: z.string().max(4096).nullable(),
  contentDigest: SafeDigestSchema.nullable(),
  correctionState: z.enum(['clean','correction_pending','corrected','retracted']).nullable(),
  updatedAt: z.number().int().min(0),
  publishedAt: z.number().int().min(0).nullable(),
  fetchedAt: z.number().int().min(0).nullable(),
  deleted: z.boolean(),
  /** Main-derived: source passes all CA eligibility checks. */
  eligible: z.boolean(),
  /** Main-derived: review status label (clean/corrected/retracted/untagged/...). */
  reviewStatus: z.string(),
  /** Main-derived: human-readable reason when ineligible. */
  reason: z.string(),
});

export const CurrentAffairsListSourcesRequestSchema = z.strictObject({
  version: z.literal(CA_RUNTIME_CONTRACT_VERSION),
  operationId: SafeIdSchema,
  projectId: SafeIdSchema,
});
export type CurrentAffairsListSourcesRequest = z.infer<typeof CurrentAffairsListSourcesRequestSchema>;

export const CurrentAffairsListSourcesResponseSchema = z.discriminatedUnion('ok', [
  z.strictObject({ ok: z.literal(true), version: z.literal(CA_RUNTIME_CONTRACT_VERSION), operationId: SafeIdSchema, sources: z.array(CASourceEntrySchema) }),
  z.strictObject({ ok: z.literal(false), version: z.literal(CA_RUNTIME_CONTRACT_VERSION), operationId: SafeIdSchema, code: z.enum(['repository_unavailable','project_not_found']) }),
]);

export function decodeCurrentAffairsListSourcesResponse(input: unknown): z.infer<typeof CurrentAffairsListSourcesResponseSchema> {
  const parsed = CurrentAffairsListSourcesResponseSchema.safeParse(input);
  return parsed.success ? parsed.data : { ok: false as const, version: CA_RUNTIME_CONTRACT_VERSION, operationId: 'decode-recovery', code: 'repository_unavailable' as const };
}

// ── Source Review ───────────────────────────────────────────────

export const SourceReviewRequestSchema = z.strictObject({
  version: z.literal(CA_RUNTIME_CONTRACT_VERSION),
  operationId: SafeIdSchema,
  projectId: SafeIdSchema,
  sourceId: SafeIdSchema,
  expectedSourceVersionHash: SafeDigestSchema,
  expectedUpdatedAt: z.number().int().min(0),
  caKind: z.enum(LISTABLE_CA_KINDS),
  correctionState: z.enum(['clean','corrected','retracted']),
  note: z.string().max(2000).optional(),
});

export const SourceReviewResponseSchema = z.discriminatedUnion('ok', [
  z.strictObject({ ok: z.literal(true), version: z.literal(CA_RUNTIME_CONTRACT_VERSION), operationId: SafeIdSchema, sourceId: SafeIdSchema, reviewed: z.literal(true), correctionState: z.enum(['clean','corrected','retracted']), reviewDigest: SafeDigestSchema }),
  z.strictObject({ ok: z.literal(false), version: z.literal(CA_RUNTIME_CONTRACT_VERSION), operationId: SafeIdSchema, sourceId: SafeIdSchema, code: z.enum(['source_not_found','cross_project','deleted','hash_mismatch','timestamp_mismatch','conflict','review_failed']) }),
]);

export type SourceReviewRequest = z.infer<typeof SourceReviewRequestSchema>;
export type SourceReviewResponse = z.infer<typeof SourceReviewResponseSchema>;

export function decodeSourceReviewResponse(input: unknown): SourceReviewResponse {
  const parsed = SourceReviewResponseSchema.safeParse(input);
  return parsed.success ? parsed.data : { ok: false as const, version: CA_RUNTIME_CONTRACT_VERSION, operationId: 'decode-recovery', sourceId: 'ca-review-recovery' as const, code: 'review_failed' as const };
}
